<?php

/**
 * @copyright Copyright (C) Ibexa AS. All rights reserved.
 * @license For full copyright and license information view LICENSE file distributed with this source code.
 */
declare(strict_types=1);

namespace Ibexa\Bundle\Cloud\DependencyInjection;

use Ibexa\Bundle\Core\Session\Handler\NativeSessionHandler;
use JsonException;
use Symfony\Component\DependencyInjection\EnvVarLoaderInterface;

final readonly class UpsunEnvVarLoader implements EnvVarLoaderInterface
{
    private const string MYSQL_DEFAULT_DATABASE_CHARSET = 'utf8mb4';

    private const string PGSQL_DEFAULT_DATABASE_CHARSET = 'utf8';

    private const string DEFAULT_DATABASE_COLLATION = 'utf8mb4_unicode_520_ci';

    public function loadEnvVars(): array
    {
        if (!isset($_SERVER['PLATFORM_RELATIONSHIPS']) || !isset($_SERVER['PLATFORM_ROUTES'])) {
            return [];
        }

        $relationshipsEncoded = $_SERVER['PLATFORM_RELATIONSHIPS'];
        $routesEncoded = $_SERVER['PLATFORM_ROUTES'];

        $relationships = $this->decodePayload($relationshipsEncoded);
        $routes = $this->decodePayload($routesEncoded);

        if ($relationships === null || $routes === null) {
            return [];
        }

        $groupedRelationships = $this->groupRelationshipsByScheme($relationships);

        return array_filter(
            array_merge(
                $this->buildDatabaseEnvVars($groupedRelationships),
                $this->buildDfsEnvVars($groupedRelationships),
                $this->buildCacheEnvVars($groupedRelationships),
                $this->buildSessionEnvVars($relationships, $groupedRelationships),
                $this->buildSearchEnvVars($relationships),
                $this->buildVarnishEnvVars($routes),
                $this->buildAppSecretEnvVars(),
            ),
            static fn (string|int|null $value): bool => $value !== null && $value !== ''
        );
    }

    /**
     * @param array<string, array<string, array<array<string, mixed>>>> $groupedRelationships
     *
     * @return array<string, string>
     */
    private function buildDatabaseEnvVars(array $groupedRelationships): array
    {
        $envVars = [];

        foreach ($groupedRelationships as $scheme => $relationshipsByKey) {
            $isPGSQL = str_starts_with($scheme, 'pgsql')
                || str_starts_with($scheme, 'postgresql')
                || str_starts_with($scheme, 'postgres');
            $isMySQL = str_starts_with($scheme, 'mysql');
            if (!$isPGSQL && !$isMySQL) {
                continue;
            }

            $normalizedScheme = $isPGSQL ? 'postgres' : 'mysql';

            foreach ($relationshipsByKey as $key => $endpoints) {
                $key = strtoupper($key);
                $endpointEnvVars = $this->buildDatabaseEndpointEnvVars($endpoints, $key, $normalizedScheme, $isMySQL);
                $envVars = array_merge($envVars, $endpointEnvVars);
            }
        }

        return $envVars;
    }

    /**
     * Builds DFS-specific env vars. Note: DFS_DATABASE_URL and other standard database
     * vars are already generated by buildDatabaseEnvVars - this only adds DFS-specific ones.
     *
     * @param array<string, array<string, array<array<string, mixed>>>> $groupedRelationships
     *
     * @return array<string, string>
     */
    private function buildDfsEnvVars(array $groupedRelationships): array
    {
        $dfsPath = $_SERVER['PLATFORMSH_DFS_NFS_PATH'] ?? null;
        if ($dfsPath === null) {
            return [];
        }

        $envVars = [
            $this->getEnvKey('dfs_nfs_path') => $dfsPath,
        ];

        // Look for 'dfs_database' relationship within mysql/pgsql schemes to determine driver and charset
        $dfsEndpoint = $this->findDfsEndpoint($groupedRelationships);

        if ($dfsEndpoint !== null) {
            $scheme = (string) ($dfsEndpoint['scheme'] ?? '');
            $isPgsql = str_starts_with($scheme, 'pgsql')
                || str_starts_with($scheme, 'postgresql')
                || str_starts_with($scheme, 'postgres');

            $envVars[$this->getEnvKey('dfs_database_driver')] = $this->normalizePdoDriver($scheme);
            $envVars[$this->getEnvKey('dfs_database_charset')] = $isPgsql
                ? self::PGSQL_DEFAULT_DATABASE_CHARSET
                : self::MYSQL_DEFAULT_DATABASE_CHARSET;

            // Collation is MySQL-specific, PostgreSQL doesn't use it
            if (!$isPgsql) {
                $envVars[$this->getEnvKey('dfs_database_collation')] = self::DEFAULT_DATABASE_COLLATION;
            }
        }

        return $envVars;
    }

    /**
     * @param array<string, array<string, array<array<string, mixed>>>> $groupedRelationships
     *
     * @return array<string, mixed>|null
     */
    private function findDfsEndpoint(array $groupedRelationships): ?array
    {
        foreach ($groupedRelationships as $scheme => $relationshipsByKey) {
            if (
                !str_starts_with($scheme, 'mysql')
                && !str_starts_with($scheme, 'pgsql')
                && !str_starts_with($scheme, 'postgresql')
                && !str_starts_with($scheme, 'postgres')
            ) {
                continue;
            }

            if (!isset($relationshipsByKey['dfs_database'])) {
                continue;
            }

            foreach ($relationshipsByKey['dfs_database'] as $endpoint) {
                if (isset($endpoint['query']['is_master']) && $endpoint['query']['is_master'] === true) {
                    return $endpoint;
                }
            }
        }

        return null;
    }

    /**
     * @param array<string, array<string, array<array<string, mixed>>>> $groupedRelationships Grouped by scheme
     *
     * @return array<string, string>
     */
    private function buildCacheEnvVars(array $groupedRelationships): array
    {
        $envVars = [];
        $cachePoolSet = false;

        // Process Redis/Valkey first (always preferred over memcached)
        foreach (['redis', 'valkey'] as $scheme) {
            if (!isset($groupedRelationships[$scheme])) {
                continue;
            }

            foreach ($groupedRelationships[$scheme] as $key => $endpoints) {
                $key = strtoupper($key);

                foreach (array_values($endpoints) as $i => $endpoint) {
                    $prefix = $this->buildPrefix($key, $i);

                    $host = $endpoint['host'] ?? '';
                    $port = $endpoint['port'] ?? 0;

                    $envVars["{$prefix}URL"] = sprintf('redis://%s:%s', $host, $port);
                    $envVars["{$prefix}HOST"] = $host;
                    $envVars["{$prefix}PORT"] = (string) $port;
                    $envVars["{$prefix}SCHEME"] = 'redis';

                    if (!$cachePoolSet) {
                        $envVars[$this->getEnvKey('cache_pool')] = 'cache.redis';
                        $envVars[$this->getEnvKey('cache_dsn')] = sprintf(
                            '%s:%d?retry_interval=3',
                            $host,
                            $port,
                        );
                        $cachePoolSet = true;
                    }
                }
            }
        }

        // Process Memcached (fallback, only sets cache_pool if redis wasn't found)
        if (isset($groupedRelationships['memcached'])) {
            foreach ($groupedRelationships['memcached'] as $key => $endpoints) {
                $key = strtoupper($key);

                foreach (array_values($endpoints) as $i => $endpoint) {
                    $prefix = $this->buildPrefix($key, $i);

                    $host = $endpoint['host'] ?? '';
                    $port = $endpoint['port'] ?? 0;

                    $envVars["{$prefix}HOST"] = $host;
                    $envVars["{$prefix}PORT"] = (string) $port;

                    if (!$cachePoolSet) {
                        trigger_deprecation(
                            'ibexa/cloud',
                            '5.0.5',
                            'Usage of Memcached is deprecated, redis is recommended',
                        );

                        $envVars[$this->getEnvKey('cache_pool')] = 'cache.memcached';
                        $envVars[$this->getEnvKey('cache_dsn')] = sprintf('%s:%d', $host, $port);
                        $cachePoolSet = true;
                    }
                }
            }
        }

        return $envVars;
    }

    /**
     * Uses Redis/Valkey-based sessions if possible. If a dedicated 'redissession' or 'valkeysession'
     * relationship is available, use that. If not, fallback to any available Redis/Valkey instance.
     *
     * @param array<string, array<array<string, mixed>>> $relationships Original relationships
     * @param array<string, array<string, array<array<string, mixed>>>> $groupedRelationships Grouped by scheme
     *
     * @return array<string, string>
     */
    private function buildSessionEnvVars(array $relationships, array $groupedRelationships): array
    {
        // First, try a dedicated 'redissession' or 'valkeysession' relationship
        foreach (['redissession', 'valkeysession'] as $relationshipKey) {
            if (!isset($relationships[$relationshipKey])) {
                continue;
            }

            foreach ($relationships[$relationshipKey] as $endpoint) {
                $scheme = $endpoint['scheme'] ?? null;
                if ($scheme !== 'redis' && $scheme !== 'valkey') {
                    continue;
                }

                return [
                    $this->getEnvKey('session_handler_id') => NativeSessionHandler::class,
                    $this->getEnvKey('session_save_path') => sprintf('%s:%d', $endpoint['host'], $endpoint['port']),
                ];
            }
        }

        // Fallback: use any available Redis/Valkey instance (by scheme)
        foreach (['redis', 'valkey'] as $scheme) {
            if (!isset($groupedRelationships[$scheme])) {
                continue;
            }

            foreach ($groupedRelationships[$scheme] as $endpoints) {
                foreach ($endpoints as $endpoint) {
                    return [
                        $this->getEnvKey('session_handler_id') => NativeSessionHandler::class,
                        $this->getEnvKey('session_save_path') => sprintf('%s:%d', $endpoint['host'], $endpoint['port']),
                    ];
                }
            }
        }

        return [];
    }

    /**
     * Builds search engine env vars.
     * Uses original relationships (not grouped) to check 'rel' field for elasticsearch.
     *
     * @param array<string, array<array<string, mixed>>> $relationships Original relationships
     *
     * @return array<string, string>
     */
    private function buildSearchEnvVars(array $relationships): array
    {
        $envVars = [];

        foreach ($relationships as $key => $endpoints) {
            $upperKey = strtoupper($key);
            $endpointEnvVars = $this->buildSearchEndpointEnvVars($endpoints, $upperKey);
            $envVars = array_merge($envVars, $endpointEnvVars);
        }

        return $envVars;
    }

    /**
     * @param array<string, array<string, mixed>> $routes
     *
     * @return array<string, string>
     */
    private function buildVarnishEnvVars(array $routes): array
    {
        $envVars = [];
        $varnishRoute = null;

        foreach ($routes as $host => $info) {
            if ($varnishRoute === null && $this->isVarnishRoute($info)) {
                $varnishRoute = $host;
            }

            if ($this->isVarnishRoute($info) && ($info['primary'] ?? false) === true) {
                $varnishRoute = $host;
                break;
            }
        }

        $skipHttpCachePurge = (bool) ($_SERVER['SKIP_HTTPCACHE_PURGE'] ?? false);

        if ($varnishRoute !== null && $skipHttpCachePurge === false) {
            $purgeServer = rtrim($varnishRoute, '/');
            $username = $_SERVER['HTTPCACHE_USERNAME'] ?? null;
            $password = $_SERVER['HTTPCACHE_PASSWORD'] ?? null;

            if ($username !== null && $password !== null) {
                $domain = parse_url($purgeServer, PHP_URL_HOST);
                if (is_string($domain) && $domain !== '') {
                    $credentials = rawurlencode($username) . ':' . rawurlencode($password);
                    $purgeServer = str_replace($domain, $credentials . '@' . $domain, $purgeServer);
                }
            }

            $envVars[$this->getEnvKey('httpcache_purge_type')] = 'varnish';
            $envVars[$this->getEnvKey('httpcache_purge_server')] = $purgeServer;
        }

        $envVars[$this->getEnvKey('httpcache_varnish_invalidate_token')] =
            ($_SERVER['HTTPCACHE_VARNISH_INVALIDATE_TOKEN'] ?? '') !== ''
                ? $_SERVER['HTTPCACHE_VARNISH_INVALIDATE_TOKEN']
                : ($_SERVER['PLATFORM_PROJECT_ENTROPY'] ?? '');

        return $envVars;
    }

    /**
     * Provides APP_SECRET fallback using PLATFORM_PROJECT_ENTROPY if APP_SECRET is not already defined.
     *
     * @return array<string, string>
     */
    private function buildAppSecretEnvVars(): array
    {
        if (($_SERVER['APP_SECRET'] ?? '') !== '' || ($_ENV['APP_SECRET'] ?? '') !== '') {
            return [];
        }

        $entropy = $_SERVER['PLATFORM_PROJECT_ENTROPY'] ?? null;
        if ($entropy === null) {
            return [];
        }

        return ['APP_SECRET' => $entropy];
    }

    /**
     * @return array<string, mixed>|null
     */
    private function decodePayload(string $payload): ?array
    {
        $decoded = base64_decode($payload, true);

        if ($decoded === false) {
            return null;
        }

        try {
            return json_decode($decoded, true, 512, JSON_THROW_ON_ERROR);
        } catch (JsonException) {
            return null;
        }
    }

    /**
     * @param array<string, array<array<string, mixed>>> $relationships
     *
     * @return array<string, array<string, array<array<string, mixed>>>>
     */
    private function groupRelationshipsByScheme(array $relationships): array
    {
        $groupedRelationships = [];
        foreach ($relationships as $key => $endpoints) {
            foreach ($endpoints as $endpoint) {
                if (!isset($endpoint['scheme'])) {
                    continue;
                }

                $groupedRelationships[$endpoint['scheme']][$key][] = $endpoint;
            }
        }

        return $groupedRelationships;
    }

    private function normalizePdoDriver(string $scheme): string
    {
        if ($scheme === '') {
            return '';
        }

        return str_starts_with($scheme, 'pdo_') ? $scheme : 'pdo_' . $scheme;
    }

    private function getEnvKey(string $parameterName): string
    {
        return strtoupper(str_replace(['.', '-'], '_', $parameterName));
    }

    private function buildPrefix(string $key, int $index): string
    {
        $prefix = $index === 0 ? "{$key}_" : "{$key}_{$index}_";

        return str_replace('-', '_', $prefix);
    }

    /**
     * @param array<string, mixed> $route
     */
    private function isVarnishRoute(array $route): bool
    {
        return ($route['type'] ?? null) === 'upstream' && ($route['upstream'] ?? null) === 'varnish';
    }

    /**
     * @param array<array<string, mixed>> $endpoints
     *
     * @return array<string, string>
     */
    private function buildDatabaseEndpointEnvVars(
        array $endpoints,
        string $key,
        string $normalizedScheme,
        bool $isMySQL,
    ): array {
        $envVars = [];

        foreach (array_values($endpoints) as $i => $endpoint) {
            $prefix = $this->buildPrefix($key, $i);

            $username = $endpoint['username'] ?? '';
            $password = $endpoint['password'] ?? '';
            $host = $endpoint['host'] ?? '';
            $port = $endpoint['port'] ?? 0;
            $path = $endpoint['path'] ?? 'main';

            $url = $this->buildDatabaseUrl($normalizedScheme, $username, $password, $host, $port, $path, $isMySQL, $endpoint);

            $envVars["{$prefix}URL"] = $url;
            $envVars["{$prefix}USER"] = $username;
            $envVars["{$prefix}USERNAME"] = $username;
            $envVars["{$prefix}PASSWORD"] = $password;
            $envVars["{$prefix}HOST"] = $host;
            $envVars["{$prefix}PORT"] = (string) $port;
            $envVars["{$prefix}NAME"] = $path;
            $envVars["{$prefix}DATABASE"] = $path;
            $envVars["{$prefix}DRIVER"] = $normalizedScheme;
            $envVars["{$prefix}SERVER"] = sprintf('%s://%s:%s', $normalizedScheme, $host, $port);
        }

        return $envVars;
    }

    /**
     * @param array<string, mixed> $endpoint
     */
    private function buildDatabaseUrl(
        string $normalizedScheme,
        string $username,
        string $password,
        string $host,
        int $port,
        string $path,
        bool $isMySQL,
        array $endpoint,
    ): string {
        $url = sprintf('%s://', $normalizedScheme);
        if ($username !== '') {
            $url .= rawurlencode($username);
            if ($password !== '') {
                $url .= ':' . rawurlencode($password);
            }
            $url .= '@';
        }
        $url .= sprintf('%s:%s/%s?sslmode=disable', $host, $port, $path);

        $charset = $isMySQL ? self::MYSQL_DEFAULT_DATABASE_CHARSET : self::PGSQL_DEFAULT_DATABASE_CHARSET;
        $url .= '&charset=' . $charset;

        $type = $endpoint['type'] ?? null;
        if ($type !== null && str_contains((string) $type, ':')) {
            [, $version] = explode(':', (string) $type, 2);

            if ($isMySQL) {
                $minor = $version === '10.2' ? 7 : 0;
                $version = "{$version}.{$minor}-MariaDB";
            }

            $url .= '&serverVersion=' . $version;
        }

        return $url;
    }

    /**
     * @param array<array<string, mixed>> $endpoints
     *
     * @return array<string, string>
     */
    private function buildSearchEndpointEnvVars(
        array $endpoints,
        string $upperKey,
    ): array {
        $envVars = [];

        foreach (array_values($endpoints) as $i => $endpoint) {
            $scheme = $endpoint['scheme'] ?? null;
            $rel = $endpoint['rel'] ?? null;
            $prefix = $this->buildPrefix($upperKey, $i);

            if ($scheme === 'solr') {
                $envVars = array_merge($envVars, $this->buildSolrEnvVars($endpoint, $prefix));
            }

            if ($rel === 'elasticsearch') {
                $envVars = array_merge($envVars, $this->buildElasticsearchEnvVars($endpoint, $prefix));
            }
        }

        return $envVars;
    }

    /**
     * @param array<string, mixed> $endpoint
     *
     * @return array<string, string>
     */
    private function buildSolrEnvVars(
        array $endpoint,
        string $prefix,
    ): array {
        $host = $endpoint['host'] ?? '';
        $port = $endpoint['port'] ?? 0;
        $path = $endpoint['path'] ?? '';

        return [
            $this->getEnvKey('search_engine') => 'solr',
            $this->getEnvKey('solr_dsn') => sprintf('http://%s:%d/%s', $host, $port, 'solr'),
            $this->getEnvKey('solr_core') => basename($path),
            "{$prefix}HOST" => $host,
            "{$prefix}PORT" => (string) $port,
            "{$prefix}NAME" => $path,
            "{$prefix}DATABASE" => $path,
        ];
    }

    /**
     * @param array<string, mixed> $endpoint
     *
     * @return array<string, string>
     */
    private function buildElasticsearchEnvVars(
        array $endpoint,
        string $prefix,
    ): array {
        $host = $endpoint['host'] ?? '';
        $port = $endpoint['port'] ?? 0;
        $scheme = $endpoint['scheme'] ?? 'http';
        $path = $endpoint['path'] ?? null;

        $dsn = sprintf('%s:%d', $host, $port);

        if (($endpoint['username'] ?? null) !== null && ($endpoint['password'] ?? null) !== null) {
            $dsn = rawurlencode($endpoint['username']) . ':' . rawurlencode($endpoint['password']) . '@' . $dsn;
        }

        if ($path !== null) {
            $dsn .= '/' . ltrim((string) $path, '/');
        }

        $url = $scheme . '://' . $host . ':' . $port;
        if ($path !== null && $path !== '') {
            $url .= $path;
        }

        $dsn = $scheme . '://' . $dsn;

        return [
            $this->getEnvKey('search_engine') => 'elasticsearch',
            $this->getEnvKey('elasticsearch_dsn') => $dsn,
            "{$prefix}URL" => $url,
            "{$prefix}HOST" => $host,
            "{$prefix}PORT" => (string) $port,
            "{$prefix}SCHEME" => $scheme,
        ];
    }
}
